apiVersion: apps/v1
kind: Deployment
metadata:
  name: my5gcore-nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my5gcore-nrf
  template:
    metadata:
      labels:
        io.kompose.network/5gcorenetwork: "true"
        app: my5gcore-nrf
    spec:
      containers:
        - args:
            - ./nrf
            - -nrfcfg
            - config/nrfcfg.conf
          env:
            - name: DB_URI
            - name: GIN_MODE
              value: release
          image: thiagogmta/nf_nrf
          name: nrf
          ports:
            - containerPort: 29510
          resources: {}
#          volumeMounts:
#            - mountPath: /my5Gcore/config/nrfcfg.conf
#              name: my5gcore-nrf-hostpath0
#            - mountPath: /my5Gcore/config/free5GC.conf
#              name: my5gcore-nrf-hostpath1
      restartPolicy: Always
#      volumes:
#        - hostPath:
#            path: /nrfcfg.conf
#          name: my5gcore-nrf-hostpath0
#        - hostPath:
#            path: /my5Gcore.conf
#          name: my5gcore-nrf-hostpath1
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my5gcore-nrf
spec:
  selector:
    app: my5gcore-nrf
  ports:
  - port: 29510
    targetPort: 29510
status:
  loadBalancer: {}

