info:
  version: 1.0.0
  description: UPF configuration

configuration:
  # debugLevel: panic|fatal|error|warn|info|debug|trace
  debugLevel: info
  ReportCaller: false

  pfcp:
    - addr: upf.my5GCore.org

  gtpu:
    - addr: upf.my5GCore.org
    # [optional] gtpu.name
    # - name: upf.5gc.nctu.me
    # [optional] gtpu.ifname
    # - ifname: gtpif

  dnn_list:
    - dnn: internet
      cidr: 60.60.0.0/24
      # [optional] apn_list[*].natifname
      # natifname: eth0
